from abc import ABC, abstractmethod
from typing import List, Optional
from app.models.video import Video, VideoStatus
from app.models.canal_candidato import CanalCandidato

class DatabaseInterface(ABC):
    @abstractmethod
    def salvar_video(self, canal_id: str, video: Video) -> None: ...
    @abstractmethod
    def listar_candidatos(self, canal_id: str) -> List[Video]: ...
    @abstractmethod
    def atualizar_status(self, canal_id: str, video_id: str, status: VideoStatus) -> None: ...
    @abstractmethod
    def atualizar_video(self, canal_id: str, video: Video) -> None: ...
    @abstractmethod
    def buscar_video(self, canal_id: str, video_id: str) -> Optional[Video]: ...
    @abstractmethod
    def atualizar_campos(self, canal_id: str, video_id: str, **campos) -> None: ...
    @abstractmethod
    def salvar_candidato_canal(self, canal_id: str, candidato: CanalCandidato) -> None: ...
    @abstractmethod
    def listar_candidatos_canal(self, canal_id: str) -> List[CanalCandidato]: ...
    @abstractmethod
    def salvar_keyword(self, canal_id: str, termo: str, volume: int, competition: float, seo_score: float) -> None: ...
